#!/usr/bin/env bash

if [[ "$@" == "" ]]
then
#  twitchy --non-interactive | cut -d"," -f2,3 | sort | awk -F"," '{ print $2 "," $1}' | column -s\, -t
#  twitchy --non-interactive | awk -F"|" '{ print $2 "|" $1 "|" $3 "|" $4 "|" $5}' | column -s\| -t
  twitchy --non-interactive | column -s\| -t
else
#  coproc ( echo 1 | twitchy -w $(echo "$@" | cut -f1) > /dev/null 2>&1)
#  coproc ( echo 1 | twitchy -w $(echo "$@" | cut -d" " -f1 ) > /dev/null 2>&1)
 coproc ( echo 1 | streamlink https://www.twitch.tv/$(echo "$@" | cut -d" " -f1 ) 360p > /dev/null 2>&1)

 exit;
fi
