#!/usr/bin/env sh
#yayinKontrol=$(twitchy --non-interactive | awk -F"|" '{ print $2 "|" $1 "|" $3 "|" $4 "|" $5 "|" $6 }' | column -s\| -t)
yayinKontrol=$(twitchy --non-interactive| awk -F"|" '{ print $1 "|" $2 "|" $3 "|" $4 "|" $5 }'  | column -s\| -t)

if [[ $yayinKontrol > 0 ]]; then
#	echo $yayinKontrol
	dunstify "$yayinKontrol"
else
#	echo "Kimse Yook"
	dunstify "Kimse Yook"
fi
