#!/usr/bin/env bash
#yayinKontrol=$(twitchy --non-interactive | awk -F"|" '{ print $2 "|" $1 "|" $3 "|" $4 "|" $5 "|" $6 }' | column -s\| -t)
Kontrol=$(twitchy --non-interactive| awk -F"|" '{ print $1 "|" $2 "|" $3 "|" $4 "|" $5 }' | column -s\| -t)
check_numbers=$(twitchy --non-interactive | awk -F"," '{ print $2 }' | wc -l)
if [[ $Kontrol > 0 ]]; then
#	echo $yayinKontrol
	notify-send -a twitchy "$Kontrol"
else
#	echo "Kimse Yook"
	notify-send -a twitchy "Kimse Yook"
fi
